# MILESTONE M2 — NHIỆM VỤ 5: PHƯƠNG ÁN B — WARD HIERARCHICAL

Notebook thực hiện Task 5 theo đúng các phần 5.0–5.9 của kế hoạch M2. Ward là comparator độc lập của K-Means, nên chỉ thay thuật toán, còn snapshot, universe, tám feature, Robust Scaling và Global K vẫn giữ nguyên.

## Phần 5.0 — Thiết lập file cấu hình Ward

Config Ward V2 được nhân bản từ master config M2 V2. Các rule phương pháp giữ nguyên, chỉ chuyển thuật toán sang `ward` và dùng Global K = 2 đã khóa từ Task 3.

In [1]:
import hashlib
import json
import shutil
import sys
import time
from datetime import datetime
from pathlib import Path

import pandas as pd
from IPython.display import display

def find_repo_root(start: Path) -> Path:
    for candidate in (start, *start.parents):
        if (candidate / "configs/experiments/m2_ward_market_only_v2.json").is_file():
            return candidate
    raise RuntimeError("Không tìm thấy repository root hoặc Ward V2 config")

ROOT = find_repo_root(Path.cwd().resolve())
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

CONFIG_PATH = ROOT / "configs/experiments/m2_ward_market_only_v2.json"
DATA_RUN = ROOT / "artifacts/cafef_primary/cafef-c8-complete-only-v2"
ARTIFACT_DIR = ROOT / "M2/artifacts/m2-task5-ward-v1"
MODELS_DIR = ROOT / "M2/models/ward"

config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
FEATURES = config["clustering"]["features"]
GLOBAL_K = config["clustering"]["k"]
MIN_ELIGIBLE = config["min_eligible_count"]

assert config["protocol_scope"] == "m2_market_only_v2"
assert config["stage"] == "M2_TASK_3_GLOBAL_K_FROZEN"
assert config["clustering"]["algorithm"] == "ward"
assert GLOBAL_K == 2

print(f"Protocol: {config['protocol_scope']} | Ward | Global K = {GLOBAL_K}")
print(f"Development: {len(config['development_snapshots'])} snapshot")
print(f"Output artifact: {ARTIFACT_DIR}")

Protocol: m2_market_only_v2 | Ward | Global K = 2
Development: 60 snapshot
Output artifact: D:\WORKPLACE\RAMC\m2-clustering-experiment\M2\artifacts\m2-task5-ward-v1

## Phần 5.1 — Lấy dữ liệu của từng snapshot

Nạp đúng 60 snapshot development từ C8 V2. Mỗi snapshot giữ membership riêng, không lấy membership của một tháng cuối áp ngược về lịch sử.

In [2]:
from delta_t1.experiments.runner import prepare_m2_market_only_snapshots

assert DATA_RUN.joinpath("manifest.json").is_file()
assert DATA_RUN.joinpath("canonical/feature_snapshots.jsonl").is_file()

started = time.time()
source_meta, prepared_snapshots = prepare_m2_market_only_snapshots(DATA_RUN, config)
print(f"Đã nạp {len(prepared_snapshots)} snapshot trong {time.time() - started:.2f}s")
print(f"Data artifact: {source_meta['artifact_id']} | {source_meta['data_version']}")

Đã nạp 60 snapshot trong 6.51s
Data artifact: cafef-c8-complete-only-v2 | CAFEF_C8_COMPLETE_ONLY_V2

## Phần 5.2 — Kiểm tra dữ liệu trước khi phân cụm

Mỗi snapshot phải có ít nhất 100 mã đủ điều kiện, đủ tám feature số hữu hạn, đúng schema và đúng ngày snapshot. Runner fail-closed trước khi trả về dữ liệu cho Ward.

In [3]:
validation = pd.DataFrame([{
    "snapshot_date": item["snapshot_date"],
    "status": item["status"],
    "eligible_count": item["eligible_count"],
    "reason": item["reason"],
} for item in prepared_snapshots])

assert len(validation) == 60
assert (validation["status"] == "ready").all(), "Có snapshot không sẵn sàng; dừng trước khi fit Ward"
assert (validation["eligible_count"] >= MIN_ELIGIBLE).all()

print(f"Universe hợp lệ: {validation.eligible_count.min()} đến {validation.eligible_count.max()} mã/snapshot")
display(validation)

Universe hợp lệ: 116 đến 955 mã/snapshot

   snapshot_date status  eligible_count reason
0     2019-01-31  ready             656   None
1     2019-02-28  ready             656   None
2     2019-03-29  ready             662   None
3     2019-04-26  ready             669   None
4     2019-05-31  ready             680   None
5     2019-06-28  ready             695   None
6     2019-07-31  ready             706   None
7     2019-08-30  ready             761   None
8     2019-09-30  ready             781   None
9     2019-10-31  ready             771   None
10    2019-11-29  ready             773   None
11    2019-12-31  ready             673   None
12    2020-01-31  ready             613   None
13    2020-02-28  ready             631   None
14    2020-03-31  ready             495   None
15    2020-04-29  ready             454   None
16    2020-05-29  ready             453   None
17    2020-06-30  ready             401   None
18    2020-07-31  ready             403   None
19    2020-08-31  ready             403   None
20    2020-09-30  ready             394   None
21    2020-10-30  ready             395   None
22    2020-11-30  ready             315   None
23    2020-12-31  ready             362   None
24    2021-01-29  ready             470   None
25    2021-02-26  ready             401   None
26    2021-03-31  ready             262   None
27    2021-04-29  ready             273   None
28    2021-05-31  ready             250   None
29    2021-06-30  ready             322   None
30    2021-07-30  ready             311   None
31    2021-08-31  ready             241   None
32    2021-09-30  ready             166   None
33    2021-10-29  ready             145   None
34    2021-11-30  ready             173   None
35    2021-12-31  ready             116   None
36    2022-01-28  ready             116   None
37    2022-02-28  ready             156   None
38    2022-03-31  ready             261   None
39    2022-04-29  ready             253   None
40    2022-05-31  ready             267   None
41    2022-06-30  ready             269   None
42    2022-07-29  ready             238   None
43    2022-08-31  ready             264   None
44    2022-09-30  ready             313   None
45    2022-10-31  ready             377   None
46    2022-11-30  ready             366   None
47    2022-12-30  ready             473   None
48    2023-01-31  ready             608   None
49    2023-02-28  ready             605   None
50    2023-03-31  ready             608   None
51    2023-04-28  ready             896   None
52    2023-05-31  ready             891   None
53    2023-06-30  ready             846   None
54    2023-07-31  ready             895   None
55    2023-08-31  ready             899   None
56    2023-09-29  ready             726   None
57    2023-10-31  ready             796   None
58    2023-11-30  ready             897   None
59    2023-12-29  ready             955   None

## Phần 5.3 — Robust Scaling theo snapshot

Mỗi snapshot có median và IQR riêng cho từng feature. Ward nhận vector sau Robust Scaling, nên khác biệt giữa Ward và K-Means chỉ đến từ thuật toán phân cụm.

In [4]:
from delta_t1.features.preprocessing import preprocess

first_snapshot = prepared_snapshots[0]
_, first_scaler = preprocess(first_snapshot["rows"], config["clustering"])
scaler_preview = pd.DataFrame([{
    "feature": feature,
    "median": first_scaler[feature]["center"],
    "IQR": first_scaler[feature]["scale"],
    "lower": first_scaler[feature]["lower"],
    "upper": first_scaler[feature]["upper"],
} for feature in FEATURES])

print(f"Robust scaler tại {first_snapshot['snapshot_date']}")
display(scaler_preview)

Robust scaler tại 2019-01-31

        feature        median           IQR     lower         upper
0        mom_21  0.000000e+00  9.894083e-02 -0.563265  8.715596e-01
1        mom_63  0.000000e+00  1.810996e-01 -0.540232  2.314968e+00
2       mom_126 -1.799230e-03  2.727560e-01 -0.636982  2.840950e+00
3       mom_252 -4.596801e-02  3.871460e-01 -0.800000  4.444702e+00
4        vol_63  4.012176e-01  3.147716e-01  0.000000  1.934825e+00
5       mdd_126 -2.307739e-01  1.800207e-01 -0.702703  0.000000e+00
6      beta_126  2.287831e-01  5.926526e-01 -1.498937  2.068618e+00
7  liquidity_21  3.669881e+07  4.819818e+08  0.000000  1.184559e+11

## Phần 5.4 — Chạy Ward với Global K

Ward chỉ fit với K = 2. Cell này không quét K và không đọc holdout. Với quyền ghi đè đã được phê duyệt, nó chỉ xóa artifact và model của chính Task 5 trước khi tạo kết quả mới.

In [5]:
from delta_t1.clustering.registry import get_algorithm
from delta_t1.experiments.runner import m2_clustering_config

OVERWRITE_EXISTING = True

for target in (ARTIFACT_DIR, MODELS_DIR):
    if target.exists():
        if not OVERWRITE_EXISTING:
            raise FileExistsError(
                f"Output đã tồn tại: {target}. Đặt OVERWRITE_EXISTING = True để chạy lại Task 5."
            )
        shutil.rmtree(target)

ARTIFACT_DIR.mkdir(parents=True, exist_ok=False)
MODELS_DIR.mkdir(parents=True, exist_ok=False)

ward = get_algorithm("ward")
cluster_config = m2_clustering_config(
    config,
    k=GLOBAL_K,
    k_range=[GLOBAL_K],
    momentum_feature="mom_63",
    risk_feature="vol_63",
)

fit_results = []
run_started = time.time()
for prepared in prepared_snapshots:
    result = ward.fit_snapshot(prepared["rows"], cluster_config)
    diagnostic = next(item for item in result["diagnostics"] if item["k"] == GLOBAL_K)
    fit_results.append((prepared, result, diagnostic))

assert len(fit_results) == len(prepared_snapshots)
print(f"Đã fit Ward K={GLOBAL_K} cho {len(fit_results)} snapshot trong {time.time() - run_started:.2f}s")

Đã fit Ward K=2 cho 60 snapshot trong 664.84s

## Phần 5.5 — Lưu cluster assignment

Mỗi mã đủ điều kiện nhận raw cluster label và aligned cluster label. Aligned label được nối giữa các tháng bằng mapping temporal, giúp Task 9 theo dõi chuyển cụm nhất quán.

In [6]:
from delta_t1.evaluation.temporal_metrics import compare

run_id = "m2-task5-ward-v1"
assignments = []
aligned_by_snapshot = {}
previous_result, previous_aligned = None, None

for prepared, result, _ in fit_results:
    snapshot_date = prepared["snapshot_date"]
    if previous_result is not None:
        mapping = compare(previous_result, result).get("mapping")
        if mapping is not None:
            current_aligned = {
                current: previous_aligned[prior]
                for current, prior in mapping.items()
            }
        else:
            current_aligned = None
    else:
        current_aligned = None

    if current_aligned is None:
        current_aligned = {
            profile["raw_cluster_id"]: profile["economic_rank"]
            for profile in result["profiles"]
        }

    aligned_by_snapshot[snapshot_date] = current_aligned
    for row, raw_cluster_id in zip(result["rows"], result["labels"]):
        assignments.append({
            "run_id": run_id,
            "snapshot_date": snapshot_date,
            "security_id": row["security_id"],
            "raw_cluster_id": raw_cluster_id,
            "aligned_cluster_id": current_aligned[raw_cluster_id],
            "data_version": source_meta["data_version"],
        })

    previous_result, previous_aligned = result, current_aligned

assignments_frame = pd.DataFrame(assignments)
assert len(assignments_frame) == int(validation["eligible_count"].sum())
display(assignments_frame.head())

,run_id,snapshot_date,security_id,raw_cluster_id,aligned_cluster_id,data_version
0,m2-task5-ward-v1,2019-01-31,KBS:HNX:ADC,0,0,CAFEF_C8_COMPLETE_ONLY_V2
1,m2-task5-ward-v1,2019-01-31,KBS:HNX:ALT,0,0,CAFEF_C8_COMPLETE_ONLY_V2
2,m2-task5-ward-v1,2019-01-31,KBS:HNX:AMC,0,0,CAFEF_C8_COMPLETE_ONLY_V2
3,m2-task5-ward-v1,2019-01-31,KBS:HNX:AME,0,0,CAFEF_C8_COMPLETE_ONLY_V2
4,m2-task5-ward-v1,2019-01-31,KBS:HNX:AMV,0,0,CAFEF_C8_COMPLETE_ONLY_V2

## Phần 5.6 — Xây cluster representative và cluster profile

Ward không tối ưu centroid như K-Means. Sau khi gán cụm, notebook tính representative bằng mean của thành viên trong cụm theo cùng quy tắc profile, cùng tám feature và schema 13 cột của M2.

In [7]:
profiles = []
scaler_rows = []

for prepared, result, _ in fit_results:
    snapshot_date = prepared["snapshot_date"]
    aligned_ids = aligned_by_snapshot[snapshot_date]

    for profile in result["profiles"]:
        profiles.append({
            "snapshot_date": snapshot_date,
            "raw_cluster_id": profile["raw_cluster_id"],
            "aligned_cluster_id": aligned_ids[profile["raw_cluster_id"]],
            "size": profile["size"],
            "size_ratio": profile["size"] / prepared["eligible_count"],
            **{feature: profile["centroid"][feature] for feature in FEATURES},
        })

    for feature in FEATURES:
        scaler_rows.append({
            "snapshot_date": snapshot_date,
            "feature": feature,
            **result["model"]["scaler"][feature],
        })

profiles_frame = pd.DataFrame(profiles)
scalers_frame = pd.DataFrame(scaler_rows)

assert list(profiles_frame.columns) == [
    "snapshot_date", "raw_cluster_id", "aligned_cluster_id",
    "size", "size_ratio", *FEATURES,
]
assert len(profiles_frame) == len(prepared_snapshots) * GLOBAL_K
assert not profiles_frame.isna().any().any()

display(profiles_frame.head())

,snapshot_date,raw_cluster_id,aligned_cluster_id,size,size_ratio,mom_21,mom_63,mom_126,mom_252,vol_63,mdd_126,beta_126,liquidity_21
0,2019-01-31,0,0,648,0.987805,0.003277,0.029398,0.048524,0.010901,0.465075,-0.253157,0.287043,1.969936e+09
1,2019-01-31,1,1,8,0.012195,0.039462,-0.007194,-0.045527,-0.178291,0.279032,-0.232461,1.139304,1.062323e+11
2,2019-02-28,0,0,651,0.992378,0.032227,0.045305,0.058408,0.039011,0.458351,-0.250515,0.278392,3.182627e+09
3,2019-02-28,1,1,5,0.007622,0.077639,0.025520,-0.072956,-0.189018,0.301457,-0.270606,1.186922,1.725316e+11
4,2019-03-29,0,0,627,0.947130,0.036937,0.062473,0.062577,0.058086,0.482040,-0.250775,0.255788,1.572620e+09

## Phần 5.7 — Tính quality metrics

Ward được đánh giá tại từng snapshot bằng Silhouette, Davies–Bouldin, Calinski–Harabasz và Cluster Balance. Inertia được lưu như chẩn đoán phụ, không dùng để chọn lại K.

In [8]:
diagnostics = []
for prepared, _, diagnostic in fit_results:
    diagnostics.append({
        "snapshot_date": prepared["snapshot_date"],
        **diagnostic,
    })

diagnostics_frame = pd.DataFrame(diagnostics)
assert len(diagnostics_frame) == len(prepared_snapshots)

quality_columns = [
    "snapshot_date", "silhouette", "davies_bouldin",
    "calinski_harabasz", "inertia", "cluster_balance",
]
display(diagnostics_frame[quality_columns])

quality_median = diagnostics_frame[
    ["silhouette", "davies_bouldin", "calinski_harabasz", "cluster_balance"]
].median().rename("median").to_frame()
display(quality_median)

,snapshot_date,silhouette,davies_bouldin,calinski_harabasz,inertia,cluster_balance
0,2019-01-31,0.949454,0.096075,2060.176839,1.173967e+05,0.012346
1,2019-02-28,0.949498,0.178409,1084.828444,2.510187e+05,0.007680
2,2019-03-29,0.883656,0.491123,1407.104752,6.315804e+04,0.055821
3,2019-04-26,0.885047,0.533150,1093.885643,9.144885e+04,0.048589
4,2019-05-31,0.972832,0.018141,741.963922,2.118663e+05,0.001473
5,2019-06-28,0.931426,0.372667,1907.928316,1.315401e+05,0.022059
6,2019-07-31,0.942458,0.265989,879.259764,2.223972e+05,0.007133
7,2019-08-30,0.944814,0.265593,1206.069632,1.779560e+05,0.007947
8,2019-09-30,0.899473,0.501253,1503.615053,1.986217e+05,0.048322
9,2019-10-31,0.903065,0.500279,1096.703828,2.348767e+05,0.033512
10,2019-11-29,0.959102,0.232186,1133.376726,4.851667e+05,0.005202
11,2019-12-31,0.962094,0.147446,1371.626523,4.314271e+05,0.005979
12,2020-01-31,0.930791,0.565397,977.120979,5.457997e+05,0.035473
13,2020-02-28,0.965668,0.139175,1301.295904,9.399389e+05,0.006380
14,2020-03-31,0.955037,0.283985,1772.938562,1.062806e+05,0.014344
15,2020-04-29,0.928567,0.263240,681.403880,7.842726e+04,0.011136
16,2020-05-29,0.871933,0.578328,772.649575,6.605831e+04,0.063380
17,2020-06-30,0.799988,0.543254,682.567191,1.256119e+04,0.080863
18,2020-07-31,0.823990,0.546656,729.524202,2.221361e+04,0.083333
19,2020-08-31,0.834445,0.508955,756.496649,1.422543e+04,0.060526
20,2020-09-30,0.877149,0.369530,805.814726,1.696455e+04,0.028721
21,2020-10-30,0.932444,0.233599,1500.992217,4.980750e+04,0.023316
22,2020-11-30,0.883824,0.223844,516.356053,2.601127e+04,0.022727
23,2020-12-31,0.789259,0.541693,674.728138,7.915656e+03,0.096970
24,2021-01-29,0.810944,0.580500,752.541718,2.020825e+04,0.090487
25,2021-02-26,0.881908,0.293798,946.576481,1.854547e+04,0.033505
26,2021-03-31,0.971393,0.122573,1048.550556,4.908524e+04,0.007692
27,2021-04-29,0.962135,0.278884,1077.288264,5.226438e+04,0.011111
28,2021-05-31,0.968078,0.315612,1262.840198,4.925339e+04,0.012146
29,2021-06-30,0.969881,0.334645,1545.546108,1.327771e+05,0.012579
30,2021-07-30,0.973464,0.139024,1732.668815,8.915270e+04,0.009740
31,2021-08-31,0.953079,0.375158,984.101136,4.206196e+04,0.016878
32,2021-09-30,0.935535,0.249718,701.814592,9.376019e+03,0.018405
33,2021-10-29,0.946678,0.032833,420.516215,8.197423e+03,0.006944
34,2021-11-30,0.897924,0.537039,304.151262,3.276639e+04,0.042169
35,2021-12-31,0.921240,0.199626,401.421689,2.085427e+03,0.017544
36,2022-01-28,0.927696,0.042427,239.393615,3.023147e+03,0.008696
37,2022-02-28,0.960926,0.021757,567.753630,1.672918e+04,0.006452
38,2022-03-31,0.820960,0.464490,319.237059,7.568400e+03,0.039841
39,2022-04-29,0.883073,0.355837,484.023446,1.264954e+04,0.028455
40,2022-05-31,0.903797,0.352845,530.670910,2.676152e+04,0.022989
41,2022-06-30,0.855118,0.550352,473.427749,5.386392e+04,0.116183
42,2022-07-29,0.892722,0.209381,372.937075,1.248591e+04,0.017094
43,2022-08-31,0.864963,0.319492,341.331162,7.259539e+03,0.019305
44,2022-09-30,0.849732,0.439681,683.710866,7.773178e+03,0.046823
45,2022-10-31,0.908148,0.482778,639.503395,9.262958e+04,0.047222
46,2022-11-30,0.891662,0.533423,607.056584,9.408917e+04,0.073314
47,2022-12-30,0.941588,0.408898,1158.149135,2.060485e+05,0.019397
48,2023-01-31,0.938815,0.489095,992.259120,9.819361e+05,0.037543
49,2023-02-28,0.938853,0.449127,1242.161413,6.651782e+05,0.037736
50,2023-03-31,0.942222,0.517540,1090.940676,8.885973e+05,0.035775
51,2023-04-28,0.965516,0.276987,1804.263811,1.244296e+06,0.006742
52,2023-05-31,0.926103,0.567302,1379.338986,9.892624e+05,0.047004
53,2023-06-30,0.963114,0.241765,2040.870932,7.847888e+05,0.008343
54,2023-07-31,0.964188,0.205571,1872.791694,6.780294e+05,0.006749
55,2023-08-31,0.973818,0.177090,1807.602337,1.326266e+06,0.004469
56,2023-09-29,0.972073,0.271648,2163.856891,3.751023e+06,0.008333
57,2023-10-31,0.965714,0.278534,1833.045953,3.281064e+06,0.010152
58,2023-11-30,0.968859,0.341257,2050.601243,5.052328e+06,0.007865
59,2023-12-29,0.949481,0.264563,2461.383215,1.192661e+06,0.015957

                        median
silhouette            0.933990
davies_bouldin        0.317552
calinski_harabasz  1020.404838
cluster_balance       0.018855

## Phần 5.8 — Lặp lại cho toàn bộ development

Các bước lọc universe, kiểm tra feature, Robust Scaling, Ward K = 2, assignment, profile và metrics đã được thực hiện độc lập cho đủ 60 snapshot development.

In [9]:
coverage = pd.DataFrame([{
    "snapshot_date": prepared["snapshot_date"],
    "eligible_count": prepared["eligible_count"],
    "assignments": sum(
        assignments_frame["snapshot_date"] == prepared["snapshot_date"]
    ),
    "profiles": sum(
        profiles_frame["snapshot_date"] == prepared["snapshot_date"]
    ),
    "diagnostics": sum(
        diagnostics_frame["snapshot_date"] == prepared["snapshot_date"]
    ),
} for prepared, _, _ in fit_results])

assert (coverage["assignments"] == coverage["eligible_count"]).all()
assert (coverage["profiles"] == GLOBAL_K).all()
assert (coverage["diagnostics"] == 1).all()

print("Coverage 60 snapshot development: PASS")
display(coverage)

Coverage 60 snapshot development: PASS

   snapshot_date  eligible_count  assignments  profiles  diagnostics
0     2019-01-31             656          656         2            1
1     2019-02-28             656          656         2            1
2     2019-03-29             662          662         2            1
3     2019-04-26             669          669         2            1
4     2019-05-31             680          680         2            1
5     2019-06-28             695          695         2            1
6     2019-07-31             706          706         2            1
7     2019-08-30             761          761         2            1
8     2019-09-30             781          781         2            1
9     2019-10-31             771          771         2            1
10    2019-11-29             773          773         2            1
11    2019-12-31             673          673         2            1
12    2020-01-31             613          613         2            1
13    2020-02-28             631          631         2            1
14    2020-03-31             495          495         2            1
15    2020-04-29             454          454         2            1
16    2020-05-29             453          453         2            1
17    2020-06-30             401          401         2            1
18    2020-07-31             403          403         2            1
19    2020-08-31             403          403         2            1
20    2020-09-30             394          394         2            1
21    2020-10-30             395          395         2            1
22    2020-11-30             315          315         2            1
23    2020-12-31             362          362         2            1
24    2021-01-29             470          470         2            1
25    2021-02-26             401          401         2            1
26    2021-03-31             262          262         2            1
27    2021-04-29             273          273         2            1
28    2021-05-31             250          250         2            1
29    2021-06-30             322          322         2            1
30    2021-07-30             311          311         2            1
31    2021-08-31             241          241         2            1
32    2021-09-30             166          166         2            1
33    2021-10-29             145          145         2            1
34    2021-11-30             173          173         2            1
35    2021-12-31             116          116         2            1
36    2022-01-28             116          116         2            1
37    2022-02-28             156          156         2            1
38    2022-03-31             261          261         2            1
39    2022-04-29             253          253         2            1
40    2022-05-31             267          267         2            1
41    2022-06-30             269          269         2            1
42    2022-07-29             238          238         2            1
43    2022-08-31             264          264         2            1
44    2022-09-30             313          313         2            1
45    2022-10-31             377          377         2            1
46    2022-11-30             366          366         2            1
47    2022-12-30             473          473         2            1
48    2023-01-31             608          608         2            1
49    2023-02-28             605          605         2            1
50    2023-03-31             608          608         2            1
51    2023-04-28             896          896         2            1
52    2023-05-31             891          891         2            1
53    2023-06-30             846          846         2            1
54    2023-07-31             895          895         2            1
55    2023-08-31             899          899         2            1
56    2023-09-29             726          726         2            1
57    2023-10-31             796          796         2            1
58    2023-11-30             897          897         2            1
59    2023-12-29             955          955         2            1

## Phần 5.9 — Lưu artifact Ward

Xuất artifact và model đã fit để Task 7 đọc quality metrics, Task 8 đọc cluster profiles, Task 9 đọc assignment/profile/scaler và Task 10 so sánh Ward với các phương án khác.

In [10]:
def write_jsonl(path: Path, rows: list[dict]) -> None:
    with path.open("w", encoding="utf-8") as stream:
        for row in rows:
            stream.write(json.dumps(row, ensure_ascii=False, allow_nan=False) + "\n")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# Xuất model Ward theo snapshot: scaler, tâm cụm scaled, linkage và metadata fit.
linkage_records = []
universe_records = []
representatives = []
cluster_sizes = []
model_index = []

for prepared, result, diagnostic in fit_results:
    snapshot_date = prepared["snapshot_date"]
    model = result["model"]
    linkage = model.get("linkage")
    assert isinstance(linkage, list)
    assert len(linkage) == prepared["eligible_count"] - GLOBAL_K

    model_path = MODELS_DIR / f"{snapshot_date}.json"
    model_document = {
        "run_id": run_id,
        "snapshot_date": snapshot_date,
        "algorithm": "ward",
        "global_k": GLOBAL_K,
        "feature_order": FEATURES,
        "eligible_count": prepared["eligible_count"],
        "model": model,
        "diagnostics": diagnostic,
    }
    model_path.write_text(
        json.dumps(model_document, ensure_ascii=False, indent=2, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    model_index.append({
        "snapshot_date": snapshot_date,
        "model_path": str(model_path.relative_to(ROOT)).replace("\\", "/"),
        "linkage_merge_count": len(linkage),
        "sha256": sha256(model_path),
    })

    for merge_index, merge in enumerate(linkage):
        linkage_records.append({
            "snapshot_date": snapshot_date,
            "merge_index": merge_index,
            **merge,
        })

    aligned_ids = aligned_by_snapshot[snapshot_date]
    for profile in result["profiles"]:
        representative = {
            "snapshot_date": snapshot_date,
            "raw_cluster_id": profile["raw_cluster_id"],
            "aligned_cluster_id": aligned_ids[profile["raw_cluster_id"]],
            "semantic_label": profile["semantic_label"],
            "economic_rank": profile["economic_rank"],
            "size": profile["size"],
            "size_ratio": profile["size"] / prepared["eligible_count"],
            **{feature: profile["centroid"][feature] for feature in FEATURES},
        }
        representatives.append(representative)
        cluster_sizes.append({
            "snapshot_date": snapshot_date,
            "raw_cluster_id": representative["raw_cluster_id"],
            "aligned_cluster_id": representative["aligned_cluster_id"],
            "size": representative["size"],
            "size_ratio": representative["size_ratio"],
        })

    for row in prepared["rows"]:
        universe_records.append({
            "snapshot_date": snapshot_date,
            "security_id": row["security_id"],
            "ticker": row.get("ticker", row["security_id"].split(":")[-1]),
            "eligibility_field": config["eligibility_field"],
            "eligible": True,
        })

assert len(universe_records) == len(assignments)
assert len(linkage_records) == int(validation["eligible_count"].sum()) - len(prepared_snapshots) * GLOBAL_K
assert len(representatives) == len(profiles_frame)
assert len(cluster_sizes) == len(profiles_frame)

representatives_frame = pd.DataFrame(representatives)
cluster_sizes_frame = pd.DataFrame(cluster_sizes)
universe_frame = pd.DataFrame(universe_records)

# JSONL là artifact chuẩn; CSV là bản thuận tiện cho kiểm tra, Task 7 và Task 8.
write_jsonl(ARTIFACT_DIR / "assignments.jsonl", assignments)
write_jsonl(ARTIFACT_DIR / "profiles.jsonl", profiles)
write_jsonl(ARTIFACT_DIR / "diagnostics.jsonl", diagnostics)
write_jsonl(ARTIFACT_DIR / "eligible_universe.jsonl", universe_records)
write_jsonl(ARTIFACT_DIR / "cluster_representatives.jsonl", representatives)
write_jsonl(ARTIFACT_DIR / "cluster_sizes.jsonl", cluster_sizes)
write_jsonl(ARTIFACT_DIR / "linkages.jsonl", linkage_records)
write_jsonl(ARTIFACT_DIR / "models_manifest.jsonl", model_index)
write_jsonl(ARTIFACT_DIR / "skipped_snapshots.jsonl", [])

assignments_frame.to_csv(ARTIFACT_DIR / "assignments.csv", index=False, encoding="utf-8")
profiles_frame.to_csv(ARTIFACT_DIR / "profiles.csv", index=False, encoding="utf-8")
profiles_frame.to_csv(ARTIFACT_DIR / "cluster_profiles.csv", index=False, encoding="utf-8")
representatives_frame.to_csv(ARTIFACT_DIR / "cluster_representatives.csv", index=False, encoding="utf-8")
cluster_sizes_frame.to_csv(ARTIFACT_DIR / "cluster_sizes.csv", index=False, encoding="utf-8")
universe_frame.to_csv(ARTIFACT_DIR / "eligible_universe.csv", index=False, encoding="utf-8")
pd.DataFrame(linkage_records).to_csv(ARTIFACT_DIR / "linkages.csv", index=False, encoding="utf-8")

# diagnostics.csv có đúng schema các Task 7 và 10 đọc trực tiếp.
diagnostics_csv = diagnostics_frame.copy()
diagnostics_csv["cluster_sizes"] = diagnostics_csv["cluster_sizes"].map(
    lambda value: json.dumps(value, sort_keys=True)
)
diagnostics_csv.to_csv(ARTIFACT_DIR / "diagnostics.csv", index=False, encoding="utf-8")
scalers_frame.to_csv(ARTIFACT_DIR / "scaler_parameters.csv", index=False, encoding="utf-8")
validation.to_csv(ARTIFACT_DIR / "snapshot_validation.csv", index=False, encoding="utf-8")
coverage.to_csv(ARTIFACT_DIR / "coverage.csv", index=False, encoding="utf-8")

# Đóng băng config và nguồn input ngay trong artifact để audit có thể chạy độc lập.
(ARTIFACT_DIR / "config.json").write_text(
    json.dumps(config, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
)
(ARTIFACT_DIR / "source_manifest.json").write_text(
    (DATA_RUN / "manifest.json").read_text(encoding="utf-8"), encoding="utf-8"
)
run_metadata = {
    "run_id": run_id,
    "stage": "M2_TASK_5_WARD_DEVELOPMENT",
    "status": "complete",
    "algorithm": "ward",
    "global_k": GLOBAL_K,
    "feature_set": FEATURES,
    "eligibility_field": config["eligibility_field"],
    "minimum_eligible_count": MIN_ELIGIBLE,
    "preprocessing": config["clustering"]["scaling"],
    "scaler_fit_scope": config["clustering"]["scaler_fit_scope"],
    "development_snapshots": config["development_snapshots"],
    "data_artifact_id": source_meta["artifact_id"],
    "data_version": source_meta["data_version"],
    "linkage_schema": ["left", "right", "distance", "size"],
    "created_at_utc": datetime.utcnow().replace(microsecond=0).isoformat() + "Z",
}
(ARTIFACT_DIR / "run_metadata.json").write_text(
    json.dumps(run_metadata, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
)

artifact_files = [path for path in sorted(ARTIFACT_DIR.iterdir()) if path.is_file()]
manifest = {
    **run_metadata,
    "development_snapshot_count": len(prepared_snapshots),
    "assignment_count": len(assignments),
    "eligible_universe_count": len(universe_records),
    "cluster_representative_count": len(representatives),
    "linkage_merge_count": len(linkage_records),
    "config_sha256": sha256(CONFIG_PATH),
    "source_manifest_sha256": sha256(DATA_RUN / "manifest.json"),
    "feature_snapshot_sha256": sha256(DATA_RUN / "canonical/feature_snapshots.jsonl"),
    "outputs": {path.name: sha256(path) for path in artifact_files},
    "models": {item["model_path"]: item["sha256"] for item in model_index},
}
(ARTIFACT_DIR / "manifest.json").write_text(
    json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
)

expected_files = {
    "assignments.jsonl", "profiles.jsonl", "diagnostics.jsonl", "manifest.json",
    "eligible_universe.jsonl", "cluster_representatives.jsonl", "cluster_sizes.jsonl",
    "linkages.jsonl", "config.json", "source_manifest.json", "run_metadata.json",
    "assignments.csv", "cluster_profiles.csv", "diagnostics.csv", "scaler_parameters.csv",
}
assert expected_files <= {path.name for path in ARTIFACT_DIR.iterdir()}
assert len(model_index) == len(prepared_snapshots)

print(f"Artifact Ward: {ARTIFACT_DIR}")
print(f"Model Ward: {MODELS_DIR}")
print(f"Assignments / universe: {len(assignments_frame):,} / {len(universe_frame):,}")
print(f"Representatives / linkage merges: {len(representatives_frame)} / {len(linkage_records):,}")
print("Audit output contract: PASS")

C:\Users\phuon\AppData\Local\Temp\ipykernel_8696\981307296.py:144: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  "created_at_utc": datetime.utcnow().replace(microsecond=0).isoformat() + "Z",

Artifact Ward: D:\WORKPLACE\RAMC\m2-clustering-experiment\M2\artifacts\m2-task5-ward-v1
Model Ward: D:\WORKPLACE\RAMC\m2-clustering-experiment\M2\models\ward
Assignments / universe: 29,907 / 29,907
Representatives / linkage merges: 120 / 29,787
Audit output contract: PASS

## Bàn giao

Task 7 dùng `diagnostics.csv`. Task 8 dùng `cluster_profiles.csv`. Task 9 dùng assignment, profile và scaler. Task 5 không mở holdout.